export const structuralCategories = [
    { name: "Pet-friendly", description: "Permiten el ingreso de mascotas" },
    { name: "WiFi", description: "Ofrecen conexión WiFi gratuita" },
    { name: "Espacio para trabajar", description: "Tienen mesas y ambiente cómodo para trabajar con notebook" },
    { name: "Abre hasta tarde", description: "Cierra después de las 22:00 horas", validateBySchedule: true },
    { name: "Abre temprano", description: "Abre antes de las 08:00 horas", validateBySchedule: true },
    { name: "Al aire libre", description: "Cuenta con espacio al aire libre o terraza" },
    { name: "Opciones vegetarianas", description: "Incluyen comidas vegetarianas" },
    { name: "Opciones veganas", description: "Incluyen opciones veganas" },
    { name: "Opciones sin gluten", description: "Ofrecen alimentos sin TACC" },
    { name: "Accesible", description: "Accesible para personas con movilidad reducida" },
    { name: "Reservas", description: "Permite hacer reservas de mesas" },
    { name: "Espacio tranquilo", description: "Ambiente silencioso, ideal para estudiar o trabajar" },
    { name: "Céntrico", description: "Ubicado en zonas céntricas de la ciudad" },
    { name: "Ideal para ir en grupo", description: "Tiene espacio suficiente para grupos grandes" },
    { name: "Ideal para ir solo", description: "Ambiente cómodo para visitar sin compañía" },
    { name: "Acepta tarjetas", description: "Acepta pagos con tarjetas de débito y/o crédito" },
    { name: "Tiene enchufes", description: "Cuenta con enchufes accesibles para cargar dispositivos" },
    { name: "Espacio techado", description: "Tiene zona techada para días de lluvia" },
    { name: "Cerca de transporte público", description: "Ubicado a pocas cuadras de paradas de ómnibus/tren" },
  ];
  
  export const perceptualCategories = [
    { name: "Ideal para trabajar", description: "Ambiente ideal para trabajar con notebook" },
    { name: "Ideal para estudiar", description: "Ambiente ideal para estudiar tranquilo" },
    { name: "Espacio cowork", description: "Zona con estilo cowork o mesas comunitarias" },
    { name: "Wi-Fi rápido", description: "Buena señal de Wi-Fi para trabajar o estudiar" },
    { name: "Apto para niños", description: "Ambiente cómodo y seguro para ir con niños" },
    { name: "Menú saludable", description: "Ofrecen opciones con ingredientes saludables" },
    { name: "Menú económico", description: "Ofrecen combos o precios accesibles" },
    { name: "Café de especialidad", description: "Preparan café de especialidad" },
    { name: "Venden café en grano", description: "Tienen café para llevar o en paquetes" },
    { name: "Tienda de café", description: "Funcionan también como tienda de café" },
    { name: "Especialistas en café", description: "El café es el foco principal del local" },
    { name: "Estilo minimalista", description: "Decoración sobria, moderna y sencilla" },
    { name: "Estilo vintage", description: "Decoración clásica o retro" },
    { name: "Instagrammeable", description: "Estética visual llamativa y cuidada" },
    { name: "Con plantas", description: "Decorado con muchas plantas y vegetación" },
    { name: "Ambiente silencioso", description: "No hay música fuerte ni ruidos molestos" },
    { name: "Ambiente relajado", description: "Tranquilo, ideal para charlar sin apuro" },
    { name: "Con música en vivo", description: "Tienen shows o música en vivo a veces" },
    { name: "Abierto fines de semana", description: "Abre sábados y domingos" },
    { name: "Cerca de parques", description: "Ubicado junto a plazas o parques verdes" },
    { name: "En el centro", description: "Ubicado en el centro de la ciudad" },
    { name: "En barrio residencial", description: "Ubicado en una zona residencial o tranquila" },
  ];
  